# Generated by Django 6.0.8 on 2026-09-12 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0005_aijob_cost_usd_aijob_input_tokens_aijob_model_name_and_more'),
        ('projects', '0001_initial'),
        ('sources', '0003_project_workspace_links'),
        ('summaries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summaries', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='summary',
            index=models.Index(fields=['project', '-created_at'], name='summary_project_date_idx'),
        ),
    ]
