# Generated by Django 6.0.8 on 2026-09-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0002_summary_project_summary_summary_project_date_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='flashcards',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
