# Generated by Django 6.0 on 2026-08-19 00:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_plans', '0001_initial'),
        ('subjects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studyplan',
            index=models.Index(fields=['user', 'status'], name='study_plan_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='studytask',
            index=models.Index(fields=['plan', 'status'], name='study_task_plan_status_idx'),
        ),
    ]
