# Generated by Django 6.0 on 2026-08-22 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0004_aifeedback_model_snapshot_and_more'),
        ('study_plans', '0003_project_workspace_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='ai_job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_plan', to='ai_integration.aijob'),
        ),
    ]
