# Generated by Django 6.0 on 2026-08-22 19:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0003_project_state_and_contract_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='aifeedback',
            name='model_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aifeedback',
            name='prompt_version_snapshot',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='aifeedback',
            name='provider_snapshot',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.CreateModel(
            name='AIJobDispatchOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatching', 'Dispatching'), ('dispatched', 'Dispatched'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_outbox', to='ai_integration.aijob')),
            ],
            options={
                'ordering': ('next_retry_at',),
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='ai_outbox_status_retry_idx')],
            },
        ),
    ]
