# Generated by Django 6.0.8 on 2026-09-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0004_aifeedback_model_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aijob',
            name='cost_usd',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='aijob',
            name='input_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aijob',
            name='model_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aijob',
            name='output_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aijob',
            name='prompt_version',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='aijob',
            name='provider_account',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='aijob',
            name='security_flags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
