# Generated by Django 6.0.8 on 2026-09-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('locale', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='ar', max_length=8)),
                ('source', models.CharField(choices=[('website', 'Marketing website')], default='website', max_length=30)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
