# Generated by Django 6.0.8 on 2026-09-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
