# Generated by Django 6.0.8 on 2026-10-02 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0006_class_library'),
        ('subjects', '0003_seed_baccalaureate_subjects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_teacher_reply', models.BooleanField(default=False)),
                ('body', models.TextField()),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-helpful_count', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('is_teacher_content', models.BooleanField(default=False)),
                ('thread_type', models.CharField(choices=[('question', 'Question'), ('explanation', 'Explanation'), ('note', 'Note'), ('method', 'Method')], default='question', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('archived', 'Archived')], db_index=True, default='open', max_length=20)),
                ('accepted_reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='knowledge.knowledgereply')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_threads', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_threads', to='organizations.classroom')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_threads', to='subjects.subject')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='knowledgereply',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='knowledge.knowledgethread'),
        ),
        migrations.CreateModel(
            name='SavedThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='knowledge.knowledgethread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='HelpfulVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='knowledge.knowledgereply')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'reply'), name='unique_helpful_vote')],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgethread',
            index=models.Index(fields=['classroom', 'status', '-created_at'], name='thread_classroom_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='savedthread',
            constraint=models.UniqueConstraint(fields=('user', 'thread'), name='unique_saved_thread'),
        ),
    ]
