# Generated by Django 6.0 on 2026-05-05 10:42

import apps.sources.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('pdf', 'PDF'), ('text', 'Text'), ('image', 'Image'), ('document', 'Document'), ('presentation', 'Presentation'), ('audio', 'Audio'), ('link', 'Link'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to=apps.sources.models.student_source_upload_to)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('extension', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_sources', to='subjects.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Source',
                'verbose_name_plural': 'Student Sources',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StudentSourceInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.CharField(choices=[('khota', 'Khota'), ('fahes', 'Fahes'), ('rasheed', 'Rasheed'), ('kholasa', 'Kholasa'), ('sada', 'Sada')], max_length=20)),
                ('action', models.CharField(choices=[('create_study_plan', 'Create Study Plan'), ('create_quiz', 'Create Quiz'), ('study_advice', 'Study Advice'), ('summarize', 'Summarize'), ('voice_help', 'Voice Help'), ('unavailable', 'Unavailable')], max_length=30)),
                ('status', models.CharField(choices=[('created', 'Created'), ('completed', 'Completed'), ('unavailable', 'Unavailable'), ('failed', 'Failed')], default='created', max_length=20)),
                ('result_type', models.CharField(blank=True, max_length=50)),
                ('result_id', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='sources.studentsource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_source_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Source Interaction',
                'verbose_name_plural': 'Student Source Interactions',
                'ordering': ('-created_at',),
            },
        ),
    ]
