# Generated by Django 6.0 on 2026-05-17 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
        ('subjects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsourceinteraction',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='sources.studentsource'),
        ),
        migrations.CreateModel(
            name='StudentSourceCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=40)),
                ('icon', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_source_collections', to='subjects.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_source_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Source Collection',
                'verbose_name_plural': 'Student Source Collections',
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
        migrations.AddField(
            model_name='studentsource',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='sources.studentsourcecollection'),
        ),
        migrations.AddField(
            model_name='studentsourceinteraction',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='sources.studentsourcecollection'),
        ),
        migrations.AddIndex(
            model_name='studentsourcecollection',
            index=models.Index(fields=['user', 'status'], name='sources_stu_user_id_954fb8_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsourcecollection',
            index=models.Index(fields=['user', 'created_at'], name='sources_stu_user_id_a02bf6_idx'),
        ),
    ]
