# Generated by Django 6.0.8 on 2026-10-02 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0006_class_library'),
        ('subjects', '0003_seed_baccalaureate_subjects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unlockable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('desk_theme', 'Desk theme'), ('desk_background', 'Desk background'), ('character_outfit', 'Character outfit')], max_length=30)),
                ('gem_requirement', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('target_value', models.PositiveIntegerField(default=1)),
                ('progress_value', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_goals', to='organizations.classroom')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SubjectPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journey_path', to='subjects.subject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PathStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('gem_reward', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='journey.subjectpath')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='UnlockedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unlockable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by', to='journey.unlockable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=60)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('week_start', models.DateField()),
                ('target_value', models.PositiveIntegerField(default=1)),
                ('gem_reward', models.PositiveIntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-week_start',),
                'constraints': [models.UniqueConstraint(fields=('code', 'week_start'), name='unique_challenge_per_week')],
            },
        ),
        migrations.CreateModel(
            name='ChallengeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('progress_value', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_progress', to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_rows', to='journey.weeklychallenge')),
            ],
        ),
        migrations.CreateModel(
            name='StationCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='journey.pathstation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'station'), name='unique_station_completion')],
            },
        ),
        migrations.CreateModel(
            name='StudentJourneyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gem_fragments_total', models.PositiveIntegerField(default=0)),
                ('current_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='journey.pathstation')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='subjects.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('subject__isnull', False)), fields=('user', 'subject'), name='unique_progress_per_subject'), models.UniqueConstraint(condition=models.Q(('subject__isnull', True)), fields=('user',), name='unique_general_progress')],
            },
        ),
        migrations.AddConstraint(
            model_name='pathstation',
            constraint=models.UniqueConstraint(fields=('path', 'order'), name='unique_station_order'),
        ),
        migrations.AddConstraint(
            model_name='unlockeditem',
            constraint=models.UniqueConstraint(fields=('user', 'unlockable'), name='unique_unlocked_item'),
        ),
        migrations.AddConstraint(
            model_name='challengeprogress',
            constraint=models.UniqueConstraint(fields=('user', 'challenge'), name='unique_challenge_progress'),
        ),
    ]
