# Generated by Django 6.0 on 2026-04-24 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('name', 'education_stage', 'grade_level'), name='unique_subject_per_stage_and_grade'),
        ),
        migrations.AddConstraint(
            model_name='usersubject',
            constraint=models.UniqueConstraint(fields=('user', 'subject'), name='unique_user_subject'),
        ),
    ]
