# Generated by Django 6.0.8 on 2026-09-12 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0005_aijob_cost_usd_aijob_input_tokens_aijob_model_name_and_more'),
        ('analytics', '0001_initial'),
        ('projects', '0001_initial'),
        ('subjects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecommendation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='studentrecommendation',
            index=models.Index(fields=['project', '-created_at'], name='recommend_project_date_idx'),
        ),
    ]
