# Generated by Django 6.0.8 on 2026-10-02 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studygroup',
            options={'ordering': ('-created_at',)},
        ),
    ]
