# Generated by Django 6.0.8 on 2026-10-01 22:20

import apps.organizations.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_reconcile_super_admin_grants'),
        ('subjects', '0003_seed_baccalaureate_subjects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLibraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('handout', 'Handout'), ('worksheet', 'Worksheet'), ('past_exam', 'Past exam paper'), ('recording', 'Approved recording'), ('other', 'Other')], db_index=True, default='handout', max_length=20)),
                ('file', models.FileField(upload_to=apps.organizations.models.class_library_upload_to)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('extension', models.CharField(blank=True, max_length=20)),
                ('source_type', models.CharField(default='other', max_length=20)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('classroom', models.ForeignKey(blank=True, help_text='Empty means every student of the organization.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library_items', to='organizations.classroom')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_items', to='organizations.organization')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_items', to='subjects.subject')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_library_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', 'status', '-created_at'], name='library_org_status_idx'), models.Index(fields=['classroom', 'status', '-created_at'], name='library_class_status_idx')],
            },
        ),
    ]
