# Generated by Django 6.0.8 on 2026-10-02 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0004_quiz_ai_job'),
        ('subjects', '0003_seed_baccalaureate_subjects'),
        ('summaries', '0003_summary_flashcards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardReviewState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('flashcard_index', models.PositiveIntegerField()),
                ('box', models.PositiveSmallIntegerField(default=0)),
                ('next_review_at', models.DateTimeField(db_index=True)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_states', to='summaries.summary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'next_review_at'], name='flashcard_review_due_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'summary', 'flashcard_index'), name='unique_flashcard_review_state')],
            },
        ),
        migrations.CreateModel(
            name='MistakeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('question_text', models.TextField()),
                ('student_answer_text', models.TextField(blank=True)),
                ('correct_answer_text', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('not_understood', 'Did not understand'), ('forgot', 'Forgot'), ('rushed', 'Rushed'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('mastered', 'Mastered')], db_index=True, default='active', max_length=20)),
                ('box', models.PositiveSmallIntegerField(default=0)),
                ('next_review_at', models.DateTimeField(db_index=True)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('mastered_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mistake_entries', to='quizzes.question')),
                ('quiz_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mistake_entries', to='quizzes.quizattempt')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mistake_entries', to='subjects.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistake_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('next_review_at',),
                'indexes': [models.Index(fields=['user', 'status', 'next_review_at'], name='mistake_user_due_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('question__isnull', False)), fields=('user', 'question'), name='unique_mistake_entry_per_question')],
            },
        ),
    ]
